import { withMenuImages } from "./menu-images";
import type { MenuItem } from "./types";

export const RESTAURANT_NAME =
  process.env.NEXT_PUBLIC_RESTAURANT_NAME ?? "Friend's Kitchen";

const RAW_MENU: Omit<MenuItem, "image">[] = [
  // —— Mains ——
  {
    id: "jollof",
    name: "Jollof Rice",
    description: "Smoky party jollof with fried plantain",
    price: 3500,
    category: "Mains",
    tags: ["rice", "spicy", "popular", "jollof"],
  },
  {
    id: "jollof-chicken",
    name: "Jollof + Chicken",
    description: "Party jollof with grilled chicken thigh",
    price: 4800,
    category: "Mains",
    tags: ["rice", "chicken", "jollof", "popular"],
  },
  {
    id: "jollof-beef",
    name: "Jollof + Beef",
    description: "Jollof rice with peppered beef",
    price: 5000,
    category: "Mains",
    tags: ["rice", "beef", "jollof"],
  },
  {
    id: "fried-rice",
    name: "Fried Rice",
    description: "Veggie fried rice with chicken",
    price: 3800,
    category: "Mains",
    tags: ["rice", "chicken"],
  },
  {
    id: "coconut-rice",
    name: "Coconut Rice",
    description: "Fragrant coconut rice with stewed protein",
    price: 4000,
    category: "Mains",
    tags: ["rice", "coconut"],
  },
  {
    id: "ofada",
    name: "Ofada Rice & Ayamase",
    description: "Local rice with green pepper sauce",
    price: 4500,
    category: "Mains",
    tags: ["rice", "ofada", "spicy"],
  },
  {
    id: "native-rice",
    name: "Native Rice",
    description: "Palm-oil native rice with seafood mix",
    price: 4200,
    category: "Mains",
    tags: ["rice", "native", "seafood"],
  },
  {
    id: "egusi",
    name: "Egusi Soup",
    description: "Thick melon-seed soup — choose swallow",
    price: 4200,
    category: "Mains",
    tags: ["soup", "swallow", "egusi"],
  },
  {
    id: "ogbono",
    name: "Ogbono Soup",
    description: "Draw soup with assorted meat",
    price: 4000,
    category: "Mains",
    tags: ["soup", "swallow", "ogbono"],
  },
  {
    id: "okro",
    name: "Okro Soup",
    description: "Fresh okro with seafood or beef",
    price: 3800,
    category: "Mains",
    tags: ["soup", "swallow", "okro"],
  },
  {
    id: "edikaikong",
    name: "Edikaikong",
    description: "Vegetable soup with periwinkle option",
    price: 4500,
    category: "Mains",
    tags: ["soup", "swallow", "vegetable"],
  },
  {
    id: "afang",
    name: "Afang Soup",
    description: "Afang leaves with assorted meats",
    price: 4500,
    category: "Mains",
    tags: ["soup", "swallow", "afang"],
  },
  {
    id: "ewedu-gbegiri",
    name: "Ewedu & Gbegiri",
    description: "With amala and assorted stew",
    price: 3900,
    category: "Mains",
    tags: ["soup", "swallow", "amala", "yoruba"],
  },
  {
    id: "pepper-soup-goat",
    name: "Goat Meat Pepper Soup",
    description: "Hot spicy broth, light and filling",
    price: 4000,
    category: "Mains",
    tags: ["soup", "spicy", "goat", "pepper soup"],
  },
  {
    id: "pepper-soup-catfish",
    name: "Catfish Pepper Soup",
    description: "Fresh catfish in spicy broth",
    price: 5500,
    category: "Mains",
    tags: ["soup", "spicy", "fish", "pepper soup"],
  },
  {
    id: "suya",
    name: "Suya Platter",
    description: "Spiced grilled beef with onions and pepper",
    price: 4500,
    category: "Mains",
    tags: ["grill", "spicy", "beef", "suya"],
  },
  {
    id: "chicken-suya",
    name: "Chicken Suya",
    description: "Grilled chicken suya strips",
    price: 4200,
    category: "Mains",
    tags: ["grill", "spicy", "chicken", "suya"],
  },
  {
    id: "chicken",
    name: "Grilled Chicken",
    description: "Half chicken, pepper sauce on the side",
    price: 5000,
    category: "Mains",
    tags: ["chicken", "grill"],
  },
  {
    id: "fried-chicken",
    name: "Fried Chicken",
    description: "Crispy fried chicken pieces",
    price: 4500,
    category: "Mains",
    tags: ["chicken", "fried"],
  },
  {
    id: "asun",
    name: "Asun",
    description: "Spicy grilled goat meat",
    price: 4800,
    category: "Mains",
    tags: ["goat", "spicy", "grill", "asun"],
  },
  {
    id: "nkwobi",
    name: "Nkwobi",
    description: "Spicy cow-foot in palm oil sauce",
    price: 5000,
    category: "Mains",
    tags: ["spicy", "nkwobi", "popular"],
  },
  {
    id: "isi-ewu",
    name: "Isi Ewu",
    description: "Spicy goat head delicacy",
    price: 6500,
    category: "Mains",
    tags: ["goat", "spicy", "isi ewu"],
  },
  {
    id: "fisherman-soup",
    name: "Fisherman Soup",
    description: "Rich seafood soup with fresh fish",
    price: 7000,
    category: "Mains",
    tags: ["soup", "seafood", "fish"],
  },
  {
    id: "yam-porridge",
    name: "Yam Porridge",
    description: "Asaro with smoked fish and palm oil",
    price: 3200,
    category: "Mains",
    tags: ["yam", "porridge", "asaro"],
  },
  {
    id: "beans-porridge",
    name: "Beans Porridge",
    description: "Ewa agoyin style soft beans",
    price: 2800,
    category: "Mains",
    tags: ["beans", "porridge", "vegetarian"],
  },
  {
    id: "spaghetti",
    name: "Stir-Fry Spaghetti",
    description: "Nigerian-style spaghetti with veggies",
    price: 3000,
    category: "Mains",
    tags: ["pasta", "spaghetti"],
  },
  {
    id: "indomie",
    name: "Special Indomie",
    description: "Indomie with egg, veggies & sausage",
    price: 2500,
    category: "Mains",
    tags: ["noodles", "indomie", "egg"],
  },
  {
    id: "shawarma-chicken",
    name: "Chicken Shawarma",
    description: "Loaded wrap with fries on the side",
    price: 3500,
    category: "Mains",
    tags: ["shawarma", "chicken", "wrap"],
  },
  {
    id: "burger",
    name: "Beef Burger",
    description: "Juicy beef patty, cheese, fries",
    price: 4000,
    category: "Mains",
    tags: ["burger", "beef", "fries"],
  },
  {
    id: "pepperoni-pizza",
    name: "Pepperoni Pizza",
    description: "12-inch oven pizza",
    price: 6500,
    category: "Mains",
    tags: ["pizza", "pepperoni"],
  },
  {
    id: "bbq-wings",
    name: "BBQ Chicken Wings",
    description: "6 pieces glazed wings",
    price: 3800,
    category: "Mains",
    tags: ["chicken", "wings", "bbq"],
  },

  // —— Swallow ——
  {
    id: "pounded-yam",
    name: "Pounded Yam",
    description: "Smooth pounded yam portion",
    price: 1500,
    category: "Swallow",
    tags: ["swallow", "yam", "poundo"],
  },
  {
    id: "eba",
    name: "Eba",
    description: "Garri eba portion",
    price: 800,
    category: "Swallow",
    tags: ["swallow", "eba", "garri"],
  },
  {
    id: "fufu",
    name: "Fufu",
    description: "Soft white fufu",
    price: 1000,
    category: "Swallow",
    tags: ["swallow", "fufu"],
  },
  {
    id: "amala",
    name: "Amala",
    description: "Hot amala portion",
    price: 1000,
    category: "Swallow",
    tags: ["swallow", "amala"],
  },
  {
    id: "semo",
    name: "Semo",
    description: "Semolina swallow",
    price: 1000,
    category: "Swallow",
    tags: ["swallow", "semo"],
  },
  {
    id: "wheat",
    name: "Wheat",
    description: "Wheat swallow portion",
    price: 1200,
    category: "Swallow",
    tags: ["swallow", "wheat"],
  },

  // —— Sides ——
  {
    id: "plantain",
    name: "Fried Plantain",
    description: "Crispy sweet plantain (dodo)",
    price: 1500,
    category: "Sides",
    tags: ["side", "plantain", "dodo", "vegetarian"],
  },
  {
    id: "moi-moi",
    name: "Moi Moi",
    description: "Steamed bean pudding",
    price: 1200,
    category: "Sides",
    tags: ["side", "moi moi", "beans", "vegetarian"],
  },
  {
    id: "colslaw",
    name: "Coleslaw",
    description: "Creamy cabbage coleslaw",
    price: 1000,
    category: "Sides",
    tags: ["side", "salad", "coleslaw"],
  },
  {
    id: "salad",
    name: "Garden Salad",
    description: "Fresh greens, tomato, cucumber",
    price: 2000,
    category: "Sides",
    tags: ["side", "vegan", "salad"],
  },
  {
    id: "fries",
    name: "French Fries",
    description: "Crispy salted fries",
    price: 1800,
    category: "Sides",
    tags: ["side", "fries", "potato"],
  },
  {
    id: "yam-chips",
    name: "Yam Chips",
    description: "Fried yam with pepper sauce",
    price: 2000,
    category: "Sides",
    tags: ["side", "yam", "chips"],
  },
  {
    id: "potato-wedges",
    name: "Potato Wedges",
    description: "Seasoned baked wedges",
    price: 2000,
    category: "Sides",
    tags: ["side", "potato"],
  },
  {
    id: "extra-meat",
    name: "Extra Assorted Meat",
    description: "Add-on meat portion",
    price: 2500,
    category: "Sides",
    tags: ["side", "meat", "protein"],
  },
  {
    id: "extra-fish",
    name: "Extra Fish",
    description: "Add-on fried or grilled fish",
    price: 3000,
    category: "Sides",
    tags: ["side", "fish", "protein"],
  },
  {
    id: "egg",
    name: "Fried Egg",
    description: "Double fried egg",
    price: 800,
    category: "Sides",
    tags: ["side", "egg"],
  },

  // —— Small chops ——
  {
    id: "puff-puff",
    name: "Puff Puff (6)",
    description: "Sweet fried dough balls",
    price: 1000,
    category: "Small chops",
    tags: ["snack", "puff puff", "sweet"],
  },
  {
    id: "spring-rolls",
    name: "Spring Rolls (4)",
    description: "Crispy veggie spring rolls",
    price: 1500,
    category: "Small chops",
    tags: ["snack", "spring rolls"],
  },
  {
    id: "samosa",
    name: "Samosa (4)",
    description: "Spiced potato samosas",
    price: 1500,
    category: "Small chops",
    tags: ["snack", "samosa"],
  },
  {
    id: "gizzard",
    name: "Peppered Gizzard",
    description: "Spicy gizzard bite plate",
    price: 2500,
    category: "Small chops",
    tags: ["snack", "gizzard", "spicy"],
  },
  {
    id: "chicken-nuggets",
    name: "Chicken Nuggets",
    description: "8 pieces with dip",
    price: 2800,
    category: "Small chops",
    tags: ["snack", "chicken", "nuggets"],
  },
  {
    id: "sharwama-small-chops",
    name: "Small Chops Platter",
    description: "Mix of puff, rolls, gizzard & more",
    price: 5500,
    category: "Small chops",
    tags: ["snack", "platter", "sharing"],
  },

  // —— Drinks ——
  {
    id: "zobo",
    name: "Zobo",
    description: "Chilled hibiscus drink",
    price: 800,
    category: "Drinks",
    tags: ["drink", "cold", "zobo"],
  },
  {
    id: "chapman",
    name: "Chapman",
    description: "Classic Nigerian mocktail",
    price: 1500,
    category: "Drinks",
    tags: ["drink", "cold", "chapman", "mocktail"],
  },
  {
    id: "smoothie-mango",
    name: "Mango Smoothie",
    description: "Fresh mango blend",
    price: 2000,
    category: "Drinks",
    tags: ["drink", "smoothie", "mango"],
  },
  {
    id: "smoothie-pineapple",
    name: "Pineapple Smoothie",
    description: "Fresh pineapple blend",
    price: 2000,
    category: "Drinks",
    tags: ["drink", "smoothie", "pineapple"],
  },
  {
    id: "fresh-orange",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed",
    price: 1800,
    category: "Drinks",
    tags: ["drink", "juice", "orange"],
  },
  {
    id: "malt",
    name: "Malt Drink",
    description: "Ice-cold bottled malt",
    price: 1000,
    category: "Drinks",
    tags: ["drink", "cold", "malt"],
  },
  {
    id: "coke",
    name: "Coca-Cola",
    description: "35cl chilled coke",
    price: 700,
    category: "Drinks",
    tags: ["drink", "soda", "coke"],
  },
  {
    id: "fanta",
    name: "Fanta",
    description: "35cl chilled fanta",
    price: 700,
    category: "Drinks",
    tags: ["drink", "soda", "fanta"],
  },
  {
    id: "sprite",
    name: "Sprite",
    description: "35cl chilled sprite",
    price: 700,
    category: "Drinks",
    tags: ["drink", "soda", "sprite"],
  },
  {
    id: "water",
    name: "Bottled Water",
    description: "Still water 75cl",
    price: 500,
    category: "Drinks",
    tags: ["drink", "water"],
  },
  {
    id: "soda-water",
    name: "Soda Water",
    description: "Sparkling soda water",
    price: 600,
    category: "Drinks",
    tags: ["drink", "soda water"],
  },
  {
    id: "hollandia",
    name: "Hollandia Yoghurt",
    description: "Chilled yoghurt drink",
    price: 1500,
    category: "Drinks",
    tags: ["drink", "yoghurt"],
  },
  {
    id: "tea",
    name: "Hot Tea",
    description: "Black or milk tea",
    price: 800,
    category: "Drinks",
    tags: ["drink", "hot", "tea"],
  },
  {
    id: "coffee",
    name: "Hot Coffee",
    description: "Fresh brewed coffee",
    price: 1000,
    category: "Drinks",
    tags: ["drink", "hot", "coffee"],
  },

  // —— Desserts ——
  {
    id: "ice-cream",
    name: "Ice Cream Cup",
    description: "Vanilla / chocolate / strawberry",
    price: 1500,
    category: "Desserts",
    tags: ["dessert", "ice cream", "sweet"],
  },
  {
    id: "chin-chin",
    name: "Chin Chin Pack",
    description: "Crunchy homemade chin chin",
    price: 1000,
    category: "Desserts",
    tags: ["dessert", "chin chin", "sweet"],
  },
  {
    id: "cake-slice",
    name: "Cake Slice",
    description: "Day’s cake — ask staff for flavour",
    price: 2000,
    category: "Desserts",
    tags: ["dessert", "cake", "sweet"],
  },
  {
    id: "fruit-salad",
    name: "Fruit Salad",
    description: "Seasonal mixed fruit bowl",
    price: 2200,
    category: "Desserts",
    tags: ["dessert", "fruit", "healthy"],
  },
];

export const DEFAULT_MENU: MenuItem[] = withMenuImages(RAW_MENU);

export function formatNaira(amount: number) {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    maximumFractionDigits: 0,
  }).format(amount);
}
